CREATE OR REPLACE FUNCTION MEDIA_IDADE_CIDADE (P_ID_CIDADE IN NUMBER) RETURN NUMBER IS
RET NUMBER;
BEGIN
    select round(avg(idade),2)
    INTO RET
    from aluno A, USUARIO U
    WHERE A.ID_USUARIO = U.ID_USUARIO AND
        U.ID_CIDADE = P_ID_CIDADE;
        
        RETURN RET;
END;

BEGIN
    DBMS_OUTPUT.PUT_LINE('MÉDIA CIDADE: ' || MEDIA_IDADE_CIDADE(4));
END;

--SELECT MEDIA_IDADE_CIDADE(3) FROM DUAL;
SELECT MEDIA_IDADE_CIDADE(ID_CIDADE) FROM CIDADE;
