CREATE OR REPLACE FUNCTION MEDIA_IDADE_CIDADE (P_ID_CIDADE IN NUMBER) RETURN NUMBER IS
RET NUMBER;
BEGIN
    select round(avg(idade),2)
    INTO RET
    from aluno A, USUARIO U
    WHERE A.ID_USUARIO = U.ID_USUARIO AND
        U.ID_CIDADE = P_ID_CIDADE;
        
        RETURN RET;
END;

BEGIN
    DBMS_OUTPUT.PUT_LINE('MÉDIA CIDADE: ' || MEDIA_IDADE_CIDADE(4));
END;

--SELECT MEDIA_IDADE_CIDADE(3) FROM DUAL;
SELECT MEDIA_IDADE_CIDADE(ID_CIDADE) FROM CIDADE;

CREATE OR REPLACE FUNCTION QUADRADO (P_NUM NUMBER) RETURN NUMBER IS
RET NUMBER;
BEGIN
    RETURN P_NUM * P_NUM;
END;

SELECT QUADRADO(9) FROM DUAL;

--   //////
CREATE OR REPLACE PROCEDURE SP_ADD_CIDADE (P_COD_CIDADE VARCHAR2, P_NOME VARCHAR2) IS
BEGIN
    INSERT INTO CIDADE (COD_CIDADE, NOME_CIDADE)
    VALUES (P_COD_CIDADE, P_NOME);
END;

EXECUTE SP_ADD_CIDADE('351830', 'Guararapes');

ROLLBACK;

SELECT * FROM CIDADE;

---> ////// <---
ALTER TABLE CIDADE ADD MEDIA_IDADE NUMBER;

SELECT * FROM ALUNO_AVALIACAO
        WHERE NOTA = 8
        ORDER BY NOTA;
        
UPDATE CIDADE 
    SET MEDIA_IDADE = MEDIA_IDADE_CIDADE(ID_CIDADE);


